FROM python:3.10-slim

RUN apt-get update
ENV SHELL /bin/bash

# install npm and python
RUN apt-get install -y \
        apt-transport-https

# install ml lib
RUN pip3 install "tensorflow==2.14.0"
RUN python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
RUN pip3 install --ignore-installed blinker # for MacOS
RUN pip3 install flask 
RUN pip3 install pandas 
RUN pip3 install "numpy<1.26"
RUN pip3 install pillow
RUN pip3 install requests
RUN pip3 install flask_cors

# copy code.
RUN mkdir /image-eval
ADD ./ /image-eval

# make donwload dir
RUN mkdir /image-eval/src/images/

EXPOSE 80

WORKDIR /image-eval
ENTRYPOINT python3 ./src/server.py 
