openapi: 3.0.0
info: 
  title: Image Quality Assessment by Ainize
  version: 0.1.1

servers: 
  - url: https://master-ainize-run-wonny-example-ainize-team.endpoint.ainize.ai

paths:
  /healthz:
    get:
      summary: API For health checking.
      responses:
        '200':
          description: OK
  /eval/image:
    post:
      summary: Returns a score of Image and Image.
      requestBody:
        content:
           application/json:
              schema:
                 type: object
                 properties:
                    url:
                       type: string
                 required:
                    - url  
      responses:
        '200': 
          description: '{ score: number }'
